# Use the official Node.js runtime image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Check if NODE_ENV=production is already in /app/.env file
RUN grep -q 'NODE_ENV=production' /app/.env || echo 'NODE_ENV=production' >> /app/.env

# Expose the port that the Express.js app will run on
EXPOSE 8080

# Command to start the Express.js application
CMD ["npm", "run", "migrate"]
